import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Next Forms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>React-Forms</h2>

    </div>
  )
}
